<?php

 /**
 * @file
 * A simple like voting widget module.
 */

/**
* Implements of hook_perm().
*/
function like_permission() {
  return array(
    'like content' =>  array(
      'title' => 'Like content',
      'description' => 'Like site content using the like voting widget.',
    ),
    'administer the like voting widget' =>  array(
      'title' => 'Administer the like widget',
      'description' => 'Make configuration changes to the like voting widget.',
    ),
  );
}

/**
* Implements of hook_menu().
*/
function like_menu() {

  $items['like/vote/%'] = array(
    'title' => 'Vote',
    'page callback' => 'like_vote',
    'page arguments' => array(2),
    'access arguments' => array('like content'),
    'type' => MENU_CALLBACK,
  );

  $items['admin/structure/like'] = array(
    'title' => 'Like',
    'description' => 'Allows readers to vote on content.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('like_settings'),
    'access arguments' => array('administer the like voting widget'),
  );

  return $items;
}

/**
* Implements of hook_init().
*/
function like_init() {
  variable_set('like_javascript_settings', 0);
}

/**
* Menu callback to configure module settings.
*/
function like_settings() {

  $form['like_nodetypes_fieldset'] = array(
    '#type' => 'fieldset',
    '#title' => t('Content type settings'),
    '#description' => t('Select all node types to which a like widget can be added.'),
  );

  $form['like_nodetypes_fieldset']['like_nodetypes'] = array(
    '#type' => 'checkboxes',
    '#options' => node_type_get_names(),
    '#default_value' => variable_get('like_nodetypes', array('article')),
  );

  $form['like_display'] = array(
    '#type' => 'fieldset',
    '#title' => t('Display settings'),
    '#description' => t('You may select none, one or both options.'),
  );

  $form['like_display']['like_in_teaser'] = array(
    '#type' => 'checkbox',
    '#title' => t('Add a like voting widget to the node in teaser view.'),
    '#default_value' => variable_get('like_in_teaser', 0),
  );

  $form['like_display']['like_in_full_view'] = array(
    '#type' => 'checkbox',
    '#title' => t('Add a like widget to the node in full view.'),
    '#default_value' => variable_get('like_in_full_view', 1),
  );

    $form['like_display']['like_in_full_view'] = array(
    '#type' => 'checkbox',
    '#title' => t('Add a like widget to the node in full view.'),
    '#default_value' => variable_get('like_in_full_view', 1),
  );

  $form['like_text'] = array(
    '#type' => 'fieldset',
    '#title' => t('Text settings'),
  );

  $form['like_text']['like_you_voted'] = array(
    '#type' => 'textfield',
    '#title' => t('Feedback provided to voter when he already voted'),
    '#default_value' => variable_get('like_you_voted', t('You voted')),
    '#description' => t('Enter, for example, <em>Dugg</em>, <em>You voted</em>, or <em>Voted</em>.'),
  );
  
  $form['like_weight'] = array(
    '#type' => 'fieldset',
    '#title' => t('Weight settings'),
  );

  $form['like_weight']['like_weight'] = array(
    '#type' => 'textfield',
    '#title' => t('Weight of voting widget'),
    '#default_value' => variable_get('like_weight', '100'),
    '#description' => t('The higher the weight the lower in the node the widget will be added. Can be a negative number.'),
  );

  $form['array_filter'] = array('#type' => 'hidden');

  return system_settings_form($form);
}

/**
* Page callback.
* @param $nid
* A node ID.
* @param $ajax
* Equal to 'json' when the function is called by jQuery.
* Submits the vote request and refreshes the page without JavaScript.
* Otherwise, it submits the vote request and returns JSON to be parsed by jQuery.
*/
function like_vote($nid) {
  global $user;
  $json = isset($_GET['json']) ? 'json' : NULL;

  $voted = like_get_votes($nid, $user->uid);
  // If the voter has not already voted.
  if (!$voted) {
    $node_type = db_select('node','n')->fields('n', array('type'))->condition('nid', $nid)->execute()->fetchObject();
    $votes[] = array(
      'entity_id' => $nid,
      'entity_type' => $node_type->type,
      'value_type' => 'points',
      'value' => 1,
    );
    votingapi_set_votes($votes);
    $criteria = array(
      'entity_id' => $nid,
      'function' => 'sum',
    );
    $results = votingapi_select_results($criteria);
    if ($json == 'json') {
      // This print statement will return results to jQuery's request.
       drupal_json_output(array('score' => $results[0]['value'], 'voted' => check_plain(variable_get('like_you_voted', t('You voted for this')))));
    }
    else {
      // Go to the full node view.
      drupal_set_message(t('Liked!.'));
      drupal_goto('node/' . $nid);
    }
  }
}

/**
* Return the number of votes for a given node ID/user ID pair.
*
* @param $nid
* A node ID.
* @param $uid
* A user ID.
* @return Integer
* Number of votes the user has cast on this node.
*/
function like_get_votes($nid, $uid) {
  $criteria['entity_id'] = $nid;
  $criteria['value_type'] = 'points';
  if ($uid == 0) {
    $criteria['vote_source'] = ip_address();
  }
  else {
    $criteria['uid'] = $uid;
  }
  $results = votingapi_select_votes($criteria);
  return count($results);
}

/**
* Return the total score of a node.
*
* @param $nid
* A node ID.
* @return Integer
* The score.
*/
function like_get_score($nid) {
  $criteria['entity_id'] = $nid;
  $criteria['value_type'] = 'points';
  $criteria['function'] = 'sum';
  $results = votingapi_select_results($criteria);
  if (empty($results)) {
    return 0;
  }
  else {
    return $results[0]['value'];
  }
}

/**
* Create like widget to display on the webpage.
*/
function like_jquery_widget($node, $teaser) {
  $score = like_get_score($node->nid);
  global $user;
  // If user is not logged-in.
  if ($user->uid == 0) {
    $logged_in = FALSE;
    $is_author = FALSE;
  }
  else {
    $logged_in = TRUE;
    $is_author = ($node->uid == $user->uid)? TRUE : FALSE;
  }
  $voted = like_get_votes($node->nid, $user->uid);
  return theme('like_widget', array('node' => $node, 'score' => $score, 'logged_in' => $logged_in, 'is_author' => $is_author, 'voted' => $voted, 'teaser' => $teaser));
  
}

/**
* Implements hook_nodeapi().
*/
function like_node_view($node, $buildmode, $langcode) {
  if (in_array($node->type, variable_get('like_nodetypes', array('article')))) {
    $teaser = variable_get('like_in_teaser', 0);
    $full  = variable_get('like_in_full_view', 1);
    if (($buildmode == 'full' && $full) || ($buildmode='teaser' && $teaser)) {
      $node->content['like_widget'] = array(
        '#markup' => like_jquery_widget($node, ($buildmode == 'teaser'), FALSE),
        '#weight' => (int) variable_get('like_weight', '100'),
      );
    }
  }
}

/**
* Implements of hook_theme().
*/
function like_theme() {
    $theme['like_widget'] = array(
        'arguments' => array('node', 'score', 'logged_in', 'is_author', 'voted', 'teaser', 'page'),
        'template' => 'like-widget',
    );
    return $theme;
}

/**
* Theme for the voting widget.
*
* You are free to load your own CSS and JavaScript files in your
* theming function override, instead of the ones provided by default.
*
* This function adds information to the Drupal.settings.like JS object,
* concerning class names used for the voting widget.
* If you override this theming function but choose to use the
* default JavaScript file, simply assign different values to
* the following variables:
*    $widget_class   (The wrapper element for the voting widget.)
*    $link_class     (The anchor element to cast a vote.)
*    $message_class  (The wrapper element for the anchor element. May contain feedback when the vote has been cast.)
*    $score_class    (The placeholder element for the score.)
* The JavaScript looks for these CSS hooks to
* update the voting widget after a vote is cast.
* Of course you may choose to write your own JavaScript.
* The JavaScript adds presentation, ie: fade in.
*
*/
function template_preprocess_like_widget(&$variables) {
   extract($variables);
  // Load the JavaScript and CSS files.
  // You are free to load your own JavaScript files in your theming function to override.
  drupal_add_js(drupal_get_path('module', 'like') . '/jquery.like.js', array('cache' => FALSE));
  drupal_add_css(drupal_get_path('module', 'like') . '/like.css');

  
  
  $variables['like']['widget_class']  = 'like-widget';
  $variables['like']['link_class']    = 'like-link';
  $variables['like']['message_class'] = 'like-msg';
  $variables['like']['score_class']   = 'like-score';
  $variables['like']['loginvote']     = l(t('Log in<br />to like this'), 'user', array('html' => TRUE));
  $variables['like']['youvoted']      = check_plain(variable_get('like_you_voted', t('You voted')));
  $variables['like']['linkvote']      = l(t('Vote for this'), 'like/vote/' . $node->nid, array('attributes' => array('class' => $variables['like']['link_class'])));

  // Attaching these hooks names to the Drupal.settings.like JavaScript object.
  // So these class names are NOT hard-coded in the JavaScript.
  if (variable_get('like_javascript_settings', 0) == 0) {
    drupal_add_js(
        array('like' => array(
          'widget_class' =>   $variables['like']['widget_class'],
          'link_class' =>  $variables['like']['link_class'] ,
          'message_class' => $variables['like']['message_class'],
          'score_class' => $variables['like']['score_class']
        )
      ), 'setting');
    variable_set('like_javascript_settings', 1);
  }
}
